### ISSUE TITLE
Firmware binary for 1.1.9?

### ISSUE THREAD

**Issue by MattGsta** [arduino/mkrwan1300-fw#16]
Hi,

Is it possible to get a compiled binary added for release 1.1.9?

Thanks!

**Comment by AmedeeBulle** [comment]
It has been released in the [MKRWAN](https://github.com/arduino-libraries/MKRWAN) project.
See [MKRWANFWUpdate_standalone](https://github.com/arduino-libraries/MKRWAN/tree/master/examples/MKRWANFWUpdate_standalone).

**Comment by facchinm** [comment]
@MattGsta you can use this (https://github.com/user-none/Bin-Headers) to convert `fw.h` into an actual binary :wink:

**Comment by MattGsta** [comment]
Thanks All!
