### ISSUE TITLE
List command AT

### ISSUE THREAD

**Issue by sabas1080** [arduino/mkrwan1300-fw#4]
Hi

Do you have any API or AT commands list to use this firmware i would be glad to have a link 

Thanks

**Comment by facchinm** [comment]
Hi @sabas1080 ,
all supported AT commands are here (https://github.com/arduino/mkrwan1300-fw/blob/master/Projects/Multi/Applications/LoRa/AT_Slave/src/command.c#L98); there's not a fancy documented list unfortunately at the moment, but it would be cool if you (or anyone else) could produce it by parsing that file and add it to the wiki :wink:
